### ISSUE TITLE
Data jump exponentially

### ISSUE THREAD

**Issue by Cactusbonus123** [retzkek/chiamon#12]
Hi!
I use  chaimon on windows. Everithing working well, but after a short amount of time (aprox. 10 min) the data from the logs jumping exponentialy. If i restart the docker machine the problem solving, but after 10 minutes (or the logs rotation time) data jumps again.

![2](https://user-images.githubusercontent.com/84245555/118394651-2afb2480-b646-11eb-8270-d220c93b2526.jpg)
UPDATE: Looks like only need chiamon_mtail restart and the dataflow is normalizing. (Some kind of buffer problem?)

**Comment by retzkek** [comment]
The quantile calculation can be a bit funny sometimes. You could try playing around with the query. Otherwise it's probably OK. I don't have the "Search Time" graph on my personal dashboard anymore, the histogram is more useful.

**Comment by Cactusbonus123** [comment]
The problem is... The Histogram is growing rapidly too, and says invalid number of data. And when the hanging appears the chiamon docker says 100% cpu to the mtail otherwise 1,5% max 20%.
![3](https://user-images.githubusercontent.com/84245555/118405043-dcfe1500-b675-11eb-8d8a-fef8b10eae72.jpg)
This 1666 data is only 2 sec on time.
![4](https://user-images.githubusercontent.com/84245555/118405129-8513de00-b676-11eb-8578-51be84ebf007.jpg)
And this is only 5 minutes later.

**Comment by retzkek** [comment]
How big is your log file? It does sound like mtail may be having some problems. Maybe an issue with the file mounts? I'd try running mtail natively instead of in Docker and see if that helps, there is a Windows binary available https://github.com/google/mtail#installation

**Comment by Cactusbonus123** [comment]
My log files are 20MB so dont know it is large or not.
And I dont know exactly how to  install mtail for windows because only one exe zipped in and i cannot configure for the docker.

**Comment by retzkek** [comment]
> My log files are 20MB so dont know it is large or not.

That's the default size for rollover, so that should be fine. 

>  And I dont know exactly how to install mtail for windows because only one exe zipped in and i cannot configure for the docker.

You would run it like the windows exporter, and change the prometheus config to scrape the metrics from it on `host.docker.internal`. Sorry, I can't really help you much more with this. mtail has some good docs on deployment and troubleshooting.

**Comment by digitalkisan** [comment]
Hi if you find a solution could you share please, as I am finding the plot data is now pulling but not updating on windows unless you restart

**Comment by Cactusbonus123** [comment]
Hi No solution yet for me. I switch to chiadog with log rotation and this solve the problem.
