### ISSUE TITLE
Please make a non docker windows version.

### ISSUE THREAD

**Issue by githubtrip** [retzkek/chiamon#18]
Docker giving nightmare. Please make a non docker windows version.

**Comment by retzkek** [comment]
Not going to happen, sorry. At least I'm not going to do it. There's lots of people working on Chia monitoring, check r/Chia or ask on Keybase chat, maybe someone has something that would work better for you.

**Comment by retzkek** [comment]
Note that nothing in this stack _requires_ Docker, you can install everything natively on Windows. You'll have to do the legwork of going through each project, downloading and installing it though.

**Comment by retzkek** [comment]
... _if_ you do decide to do that legwork, I'm sure others would really appreciate a howto or script documenting and/or automating the process. I'd be happy to link to or incorporate it into this repo.
