### ISSUE TITLE
chia_exporter problem

### ISSUE THREAD

**Issue by dEMonaRE** [retzkek/chiamon#19]
chia_exporter composes up and runing at console bot docker cant deploy it i gave the all -read-write auth but it exits all the time without error.
Also log level converted to info but no chia logs :(
any ideas? thanks in advance
![image](https://user-images.githubusercontent.com/4335569/118541601-90403a00-b75a-11eb-8911-1377586c422e.png)
![image](https://user-images.githubusercontent.com/4335569/118541941-fe84fc80-b75a-11eb-96aa-074cf8cbcb0d.png)

**PROJECT LOG**
Building mtail
[+] Building 1.5s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                   1.1s
 => [internal] load metadata for docker.io/library/golang:alpine                                                   1.2s
 => [builder 1/3] FROM docker.io/library/golang:alpine@sha256:4dd403b2e7a689adc5b7110ba9cd5da43d216cfcfccfbe2b356  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 35B                                                                                   0.0s
 => [stage-1 1/3] FROM docker.io/library/alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e  0.0s
 => CACHED [builder 2/3] WORKDIR /build                                                                            0.0s
 => CACHED [builder 3/3] RUN apk add --update --no-cache --virtual build-dependencies git make  && git clone http  0.0s
 => CACHED [stage-1 2/3] COPY --from=builder /build/mtail/usr/local/bin/mtail /usr/bin/mtail                       0.0s
 => CACHED [stage-1 3/3] COPY *.mtail /etc/mtail/                                                                  0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:707b7529ec7ed655d7192c04d75c457636ccadc9dfe9cedd3891ab6f96f179fd                       0.0s
 => => naming to docker.io/library/chiamon_mtail                                                                   0.0s
Building chia_exporter
[+] Building 0.8s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                   0.4s
 => [internal] load metadata for docker.io/library/golang:alpine                                                   0.5s
 => [builder 1/3] FROM docker.io/library/golang:alpine@sha256:4dd403b2e7a689adc5b7110ba9cd5da43d216cfcfccfbe2b356  0.0s
 => [stage-1 1/2] FROM docker.io/library/alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e  0.0s
 => CACHED [builder 2/3] WORKDIR /build                                                                            0.0s
 => CACHED [builder 3/3] RUN apk add --update --no-cache --virtual build-dependencies git make  && git clone http  0.0s
 => CACHED [stage-1 2/2] COPY --from=builder /build/chia_exporter/chia_exporter /usr/bin/chia_exporter             0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:cc21dfc65c2cebd8310d9bef2b3343641212c2c811a9eda740ee5595cd2b87c8                       0.0s
 => => naming to docker.io/library/chiamon_chia_exporter                                                           0.0s
Building prometheus
[+] Building 1.6s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 31B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/prom/prometheus:latest                                                  1.2s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 36B                                                                                   0.0s
 => [1/2] FROM docker.io/prom/prometheus@sha256:d1a9a86b9a3e60a9ea3cde141bdc936847456acc497e0affe7e288234383efa5   0.0s
 => CACHED [2/2] COPY prometheus.yml /etc/prometheus/prometheus.yml                                                0.0s
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:314e9b91e782886c652a9674baa561c12ad2b938574990453dd51d5b7cd235e3                       0.0s
 => => naming to docker.io/library/chiamon_prometheus                                                              0.0s
Building grafana
[+] Building 1.8s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.2s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.2s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/grafana/grafana:latest                                                  1.1s
 => [1/4] FROM docker.io/grafana/grafana@sha256:09bb407e26abc38cf010fcac8e13910491213e60278f07878b335257b6f844c1   0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 196B                                                                                  0.0s
 => CACHED [2/4] COPY dashboards /etc/grafana/dashboards/                                                          0.0s
 => CACHED [3/4] COPY dashboards.yaml /etc/grafana/provisioning/dashboards/                                        0.0s
 => CACHED [4/4] COPY datasources.yaml /etc/grafana/provisioning/datasources/                                      0.0s
 => exporting to image                                                                                             0.2s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:a08370f9d1c977cc521c00b0f0bfe27f607b907c508b6058ebac29b357386559                       0.0s
 => => naming to docker.io/library/chiamon_grafana                                                                 0.0s
chiamon_prometheus_1 is up-to-date
Starting chiamon_chia_exporter_1 ...
chiamon_mtail_1 is up-to-date
Starting chiamon_chia_exporter_1 ... done

**Comment by retzkek** [comment]
`read /etc/chia.key: is a directory` means that the path to the key is not correct in `docker-compose.yml`. You have to change the paths to your home directory (and make sure the rest of it is correct too).

**Comment by dEMonaRE** [comment]
You were right my mistake 
But there is another issue then : I have 2 different keys on same machine 👯 
I dont think this needed to support multiple keys atleast how can I parse or get/parse first/any column?

**ERROR: for chia_exporter  Cannot create container for service chia_exporter: Mount denied:
The source path "6026d9b67f9f4362a675d1ef3eafb193242a8bcb90a0054b3b2b3e71c7a858b1:c:/Users/aemre/.chia/mainnet/config/ssl/full_node/private_full_node.key:rw"
too many colons**

**Comment by retzkek** [comment]
>  I have 2 different keys on same machine 

Do you mean Chia keys? The files we're using here are an SSL X509 cert and key pair, very different. 

> ERROR: for chia_exporter Cannot create container for service chia_exporter: Mount denied:

Paste the `volumes:` lines from the `chia_exporter` service in your docker-compose file (or the whole service). If it's not a configuration error then I don't really know. You are running this with Docker Desktop on Windows right?
