### ISSUE TITLE
Cannot login anymore

### ISSUE THREAD

**Issue by gcraenen** [retzkek/chiamon#23]
Hi after rebooting the chia farmer and restarting chia I cannot seem to log into Grafana anymore. The default credntials also won't work. Is there a way to manaully (re)set the credentials? I can access the server it's running on at root level.

**Comment by gcraenen** [comment]
Never mind. I killed everything and started up fresh.

**Comment by retzkek** [comment]
Glad you figured out a solution. For future reference, Grafana does include a CLI that among other things can reset the admin password: https://grafana.com/docs/grafana/latest/administration/cli/#reset-admin-password
