### ISSUE TITLE
After updating Chia to 1.1.6, the netspace and status views have been lost. 

### ISSUE THREAD

**Issue by Liberticide** [retzkek/chiamon#24]
Hello, 
I updated Chia yesterday, and after updating I lost the netspace and status views.
I changed the view and noticed that the chia_blockchain_ * data is no longer available.
Do you have any idea to solve the problem?
Bye and thank you for the work :)

**Comment by retzkek** [comment]
You need to update chia_exporter: 
```
docker-compose build --no-cache chia_exporter
docker-compose up -d --force-recreate chia_exporter
```

(The netspace got so big it overflowed the type the size was being stored in)

**Comment by Liberticide** [comment]
It's OK.
Thank you
