### ISSUE TITLE
Some mounts are not shown in the list

### ISSUE THREAD

**Issue by keckj** [retzkek/chiamon#3]
My field disk is mounted to `/mnt/fields/0` and this mountpoint does not show up in mounts, and thus I cannot track disk usage. 
I imagine I have to tweak something in `grafana/dashboards/Chia.json` but I cannot determine where `$mounts` is defined.

![Sélection_446](https://user-images.githubusercontent.com/5702974/117451006-3d88a600-af42-11eb-81ea-15f19a35fdc9.png)
![Sélection_445](https://user-images.githubusercontent.com/5702974/117450777-fa2e3780-af41-11eb-9245-2daf896c5790.png)

**Comment by retzkek** [comment]
The [variables](https://grafana.com/docs/grafana/latest/variables/) are defined in the dashboard settings (click the gear icon in the upper-right corner). The variable is populated when the dashboard is loaded from the labels on the `node_filesystem_size` metric in Prometheus. 

![Screenshot from 2021-05-07 08-10-11](https://user-images.githubusercontent.com/1627510/117454406-b91b3080-af0b-11eb-8ead-28443cd54c32.png)

It's likely that the node exporter isn't seeing the mounts. Are you running it in a container? What platform are you on?

**Comment by keckj** [comment]
My host is an ubuntu 20.04, and I run it with `docker-compose up -d`.  In the prometheus node_exporter [docs](https://github.com/prometheus/node_exporter) it is said that "any non-root mount points you want to monitor will need to be bind-mounted into the container" so I suppose I just have to modify the `docker-compose.yml` to add mount points !

**Comment by retzkek** [comment]
Oh, I  thought it picked up the other mounts by having root bind-mounted into the container. In production I run the exporter natively (`sudo apt install prometheus-node-exporter`) so I didn't notice that.

**Comment by keckj** [comment]
Thanks it works with the native exporter. I had to give read and execute rights on the mount to the prometheus user.
This can also be achieved by modifying user/group in `/etc/systemd/system/multi-user.target.wants/prometheus-node-exporter.service`. Node exporter options can be edited in `/etc/default/prometheus-node-exporter`. This file can be used to tweak `collector.diskstats.ignored-devices` and `collector.filesystem.ignored-mount-points`.

**Comment by retzkek** [comment]
Thanks, that's a helpful tip (personally I just have my Chia volumes set `chmod 777` since I'm lazy 😃). I'll link to this issue from the README.
