### ISSUE TITLE
mtail does not parse windows chia debug.log due to CRLF

### ISSUE THREAD

**Issue by pikolos** [retzkek/chiamon#32]
It seems the regex in chialog.mtail does not parse log files created under windows with CRLF. Adding \r to at the end seems to fix it but breaks it for use with files created linux.

See: https://github.com/google/mtail/issues/518

**Comment by retzkek** [comment]
Sorry, I'm catching up on issues. The [mtail program in the `windows` branch](https://raw.githubusercontent.com/retzkek/chiamon/windows/mtail/chialog.mtail) should handle both line endings.
