### ISSUE TITLE
Running on Mac?

### ISSUE THREAD

**Issue by pelcasandra** [retzkek/chiamon#4]
On a Mac, if I run `docker compose up` I get:

```
Error response from daemon: path / is mounted on / but it is not a shared or slave mount
```

If I instead `brew install node_exporter` and the run `node_exporter` I can see it running:

```
level=info ts=2021-05-08T14:38:34.107Z caller=node_exporter.go:195 msg="Listening on" address=:9100
level=info ts=2021-05-08T14:38:34.108Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
```

However it is unclear what should I change now in `docker-compose.yml` to communicate with this process instead of the docker `node_exporter` service already defined. 

Any help is appreciated.

**Comment by retzkek** [comment]
Comment out or remove the `node_exporter` service from `docker-compose.yml`, that should be it. You can open the Prometheus interface at http://localhost:9090 then go to Status->Targets to check if it's able to talk to everything.

**Comment by pelcasandra** [comment]
Uncommenting `node_exporter` from `docker-compose.yml` and running `docker composer down` and `docker compose up` returns: `no such service: node_exporter`.

**Comment by retzkek** [comment]
Paste your modified docker-compose. Maybe a zombie container, run `docker rm chiamon_node_exporter_1` (or whatever name `docker ps -a` shows)

**Comment by pelcasandra** [comment]
Running now:

```
grafana_1        | {"@level":"debug","@message":"datasource: registering query type fallback handler","@timestamp":"2021-05-08T20:39:42.756085Z"}
grafana_1        | t=2021-05-08T20:39:42+0000 lvl=info msg="inserting datasource from configuration " logger=provisioning.datasources name=Prometheus uid=my_unique_uid
grafana_1        | t=2021-05-08T20:39:42+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
```

Also node_exporter is running:

```
level=info ts=2021-05-08T20:14:33.694Z caller=node_exporter.go:195 msg="Listening on" address=:9100
level=info ts=2021-05-08T20:14:33.696Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
```

But either http://localhost:9090 or http://localhost:3000 do not load. Any idea?

**Comment by retzkek** [comment]
You probably need to expose the ports. Take a look at the compose file I modified for windows https://github.com/retzkek/chiamon/blob/windows/docker-compose.yml
