### ISSUE TITLE
Get "http://localhost:9133/metrics": dial tcp 127.0.0.1:9133: connect: connection refused

### ISSUE THREAD

**Issue by LolCatPhd** [retzkek/chiamon#5]
![image](https://user-images.githubusercontent.com/29475177/117555881-5ccb2480-b063-11eb-8724-b464812cb392.png)

This is the target status I get on Prometheus.
I have chia full node GUI running.

![image](https://user-images.githubusercontent.com/29475177/117556054-2b535880-b065-11eb-91f0-88761cb384c5.png)

**Comment by retzkek** [comment]
Is `chia_exporter` running (run `docker-compose ps`)? If not run `docker-compose logs chia_exporter` and paste the output here.

**Comment by LolCatPhd** [comment]
![image](https://user-images.githubusercontent.com/29475177/117556269-52128e80-b067-11eb-8ad0-badfaf85db6e.png)

**Comment by retzkek** [comment]
Check the cert and key path in `docker-compose.yml`. You probably need to replace `${HOME}` with your home directory, since you're running `docker-compose` as root (you wouldn't have to do that if you added your user to the `docker` group).

**Comment by EclipzzeX** [comment]
I had very similar results with the metrics gathered, until I put the running user into the docker group and ran the `docker-compose` as that user vs `sudo docker-compose up -d`

`sudo usermod -a -G docker username`
