### ISSUE TITLE
Docker won't show chia metrics

### ISSUE THREAD

**Issue by ricardoleal** [retzkek/chiamon#6]
![image](https://user-images.githubusercontent.com/1679823/117731470-16ea9980-b1e6-11eb-8308-317c845645d9.png)

**Comment by retzkek** [comment]
Stick to the Chia GUI, you can switch it to "pirate" language if it's too boring. Or do a little research and troubleshooting and then open an issue that I can actually help you with.

**Comment by ricardoleal** [comment]
i've seen the mtail is not picking the logs and returns 0.
