### ISSUE TITLE
Hello  ihave this error only for chia exporter

### ISSUE THREAD

**Issue by Roken120** [retzkek/chiamon#7]
![image](https://user-images.githubusercontent.com/16229805/118054760-22c19180-b387-11eb-900a-1a83cedfbcf4.png)

**Comment by retzkek** [comment]
What platform are you on? Please paste the chia_exporter logs (`docker-compose logs chia_exporter`).

**Comment by Roken120** [comment]
My plateform is windows, i have not logs ?

**Comment by retzkek** [comment]
Are you using the config from the `windows` branch? Did you read the notes?
